# Generated by Django 3.1.1 on 2020-09-29 16:39

from django.db import migrations
import userauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', userauth.models.UserManager()),
            ],
        ),
    ]
