# Generated by Django 3.1.1 on 2020-10-01 13:11

from django.db import migrations, models
import userauth.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20200929_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=30, validators=[userauth.validators.validate_name]),
        ),
    ]
