# Generated by Django 3.1.1 on 2020-09-24 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20200920_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, max_length=1500, null=True, upload_to='images/'),
        ),
    ]
