# Generated by Django 3.1.1 on 2020-09-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_otpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, max_length=1500, null=True, upload_to='images/'),
        ),
    ]
