# Generated by Django 3.1.1 on 2020-09-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20200924_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpmodel',
            name='time_created',
        ),
    ]
