# Generated by Django 3.1.1 on 2020-10-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20201001_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, max_length=1500, null=True, upload_to=''),
        ),
    ]
