# Generated by Django 3.1.1 on 2020-09-24 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_remove_otpmodel_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
