# Generated by Django 3.1.1 on 2020-09-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20200927_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpmodel',
            name='is_teacher',
        ),
    ]
