# Generated by Django 3.1.1 on 2020-09-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_otpmodel_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='time_created',
            field=models.DateTimeField(),
        ),
    ]
