# Generated by Django 3.1.1 on 2020-09-25 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_auto_20200925_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
