# Generated by Django 3.1.1 on 2020-09-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_otpmodel_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpmodel',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_teacher',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
