# Generated by Django 3.1.1 on 2020-09-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_auto_20200925_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='time_created',
            field=models.IntegerField(),
        ),
    ]
