# Generated by Django 3.1.1 on 2020-09-22 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0002_auto_20200920_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=50, unique=True)),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_code', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('standard', models.CharField(max_length=10)),
                ('branch', models.CharField(blank=True, max_length=50)),
                ('section', models.CharField(default='1', max_length=5)),
                ('student', models.ManyToManyField(related_name='Student', to='userauth.UserProfile', verbose_name='Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher', to='userauth.userprofile', verbose_name='Teacher')),
            ],
        ),
    ]
