# Generated by Django 3.1.1 on 2020-10-11 08:11

import classes.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_linked', models.FileField(max_length=1500000, null=True, upload_to='class/answers', validators=[classes.validators.validate_file_extension])),
                ('marks_scored', models.PositiveIntegerField(default=0)),
                ('late_submitted', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('submit_by', models.DateTimeField(blank=True, null=True)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('file_linked', models.FileField(max_length=1500000, null=True, upload_to='class/assignment', validators=[classes.validators.validate_file_extension])),
            ],
            options={
                'ordering': ('-time_created',),
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=50, unique=True)),
                ('subject_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='DoubtSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('doubt_text', models.TextField(max_length=800)),
                ('file', models.FileField(blank=True, max_length=1500000, null=True, upload_to='doubt-pdf/', validators=[classes.validators.validate_file_extension])),
            ],
            options={
                'ordering': ('-time_created',),
            },
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=500)),
                ('file', models.FileField(blank=True, max_length=500000, null=True, upload_to='privatechat/', validators=[classes.validators.validate_file_extension])),
            ],
            options={
                'ordering': ('-time_created',),
            },
        ),
        migrations.CreateModel(
            name='PrivateComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=300)),
            ],
            options={
                'ordering': ['time_created'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1000)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('questions_count', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=70, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('shared', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='QuizTakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by', to='classes.quiz')),
            ],
        ),
    ]
