# Generated by Django 3.1.1 on 2020-09-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20200920_2239'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='Student', to='userauth.UserProfile', verbose_name='Student'),
        ),
    ]
