# Generated by Django 3.1.1 on 2020-09-29 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubtsection',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubt', to='classes.classroom', verbose_name='Classroom'),
        ),
    ]
