# Generated by Django 3.1.1 on 2020-10-11 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatecomment',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_received', to='userauth.userprofile'),
        ),
        migrations.AddField(
            model_name='privatecomment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_sent', to='userauth.userprofile'),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatprivate', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieverprofile', to='userauth.userprofile'),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderprofile', to='userauth.userprofile'),
        ),
        migrations.AddField(
            model_name='doubtsection',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubt', to='classes.classroom', verbose_name='Classroom'),
        ),
        migrations.AddField(
            model_name='doubtsection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='userauth.userprofile', verbose_name='UserProfile'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='ClassStudent', to='userauth.UserProfile', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClassTeacher', to='userauth.userprofile', verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersheet', to='classes.assignment'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersheet', to='userauth.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('title', 'classroom')},
        ),
    ]
