# Generated by Django 3.1.1 on 2020-10-01 12:12

import classes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200929_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='file_linked',
            field=models.FileField(max_length=1500000, null=True, upload_to='class/answers', validators=[classes.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file_linked',
            field=models.FileField(max_length=1500000, null=True, upload_to='class/assignment', validators=[classes.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='doubtsection',
            name='file',
            field=models.FileField(blank=True, max_length=1500, null=True, upload_to='doubt-pdf/', validators=[classes.validators.validate_file_extension]),
        ),
    ]
