# Generated by Django 3.1.1 on 2020-10-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20201008_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubtsection',
            name='is_private',
        ),
    ]
