# Generated by Django 3.1.1 on 2020-09-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200923_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='section',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='subject_code',
        ),
    ]
