# Generated by Django 3.1.1 on 2020-10-07 01:40

import classes.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20201007_0006'),
        ('classes', '0002_auto_20201006_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=500)),
                ('file', models.FileField(max_length=500000, null=True, upload_to='privatechat/', validators=[classes.validators.validate_file_extension])),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatprivate', to='classes.classroom')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieverprofile', to='userauth.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderprofile', to='userauth.userprofile')),
            ],
        ),
    ]
