# Generated by Django 3.1.1 on 2020-09-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('classes', '0002_auto_20200926_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='student', to='userauth.UserProfile', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='userauth.userprofile', verbose_name='Teacher'),
        ),
    ]
