# Generated by Django 3.1.1 on 2020-10-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20201001_1742'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('classroom', 'title'), name='unique_title_of_assignment_in_a_classroom'),
        ),
    ]
