# Generated by Django 3.1.1 on 2020-10-07 02:21

import classes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_privatechat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechat',
            name='file',
            field=models.FileField(blank=True, max_length=500000, null=True, upload_to='privatechat/', validators=[classes.validators.validate_file_extension]),
        ),
    ]
