# Generated by Django 3.1.1 on 2020-10-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_doubtsection_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubtsection',
            name='doubt_text',
            field=models.TextField(max_length=800),
        ),
    ]
