# Generated by Django 3.1.1 on 2020-10-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20201007_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatechat',
            options={'ordering': ('-time_created',)},
        ),
    ]
