# Generated by Django 3.1.1 on 2020-10-10 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('classes', '0004_auto_20201010_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztakers',
            name='completed',
        ),
        migrations.AlterField(
            model_name='quiztakers',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_taken', to='userauth.userprofile'),
        ),
    ]
