# Generated by Django 3.1.1 on 2020-09-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_answersheet_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
