# Generated by Django 3.1.1 on 2020-10-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20201008_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doubtsection',
            options={'ordering': ('-time_created',)},
        ),
    ]
