# Generated by Django 3.1.1 on 2020-10-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20201001_1757'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignment',
            name='unique_title_of_assignment_in_a_classroom',
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('title', 'classroom')},
        ),
    ]
