# Generated by Django 3.1.1 on 2020-09-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_userprofile_is_teacher'),
        ('classes', '0005_answersheet_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='ClassStudent', to='userauth.UserProfile', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClassTeacher', to='userauth.userprofile', verbose_name='Teacher'),
        ),
    ]
