# Generated by Django 3.1.1 on 2020-10-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20201005_0926'),
        ('classes', '0005_auto_20201001_1808'),
    ]

    operations = [
    ]
