# Generated by Django 3.1.1 on 2020-10-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200929_1248'),
        ('classes', '0005_auto_20201001_1808'),
    ]

    operations = [
    ]
