# Generated by Django 3.1.1 on 2020-10-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20201007_2050'),
        ('classes', '0006_merge_20201006_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='marks_scored',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_marks',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='PrivateComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=300)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chats', to='classes.assignment')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_received', to='userauth.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_sent', to='userauth.userprofile')),
            ],
            options={
                'ordering': ['time_created'],
            },
        ),
    ]
