# Generated by Django 3.1.1 on 2020-10-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20201001_1841'),
        ('classes', '0006_merge_20201006_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChatOnAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=300)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chats', to='classes.assignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chats', to='userauth.userprofile')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chats', to='classes.classroom')),
            ],
            options={
                'ordering': ['time_created'],
            },
        ),
    ]
