# Generated by Django 3.1.1 on 2020-10-06 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20201001_1841'),
        ('classes', '0008_auto_20201006_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatecomment',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_received', to='userauth.userprofile'),
        ),
        migrations.AlterField(
            model_name='privatecomment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_sent', to='userauth.userprofile'),
        ),
    ]
