# Generated by Django 3.1.1 on 2020-09-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('date_time', models.DateTimeField(null=True)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
