# Generated by Django 3.1.1 on 2020-10-02 21:06

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('date_time'), nulls_last=True)]},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='done',
        ),
    ]
