# Generated by Django 3.1.1 on 2020-10-05 18:41

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('date_time'), nulls_last=True)]},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='done',
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
