# Generated by Django 3.1.1 on 2020-10-08 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='userauth.userprofile'),
        ),
        migrations.AddField(
            model_name='forum',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmarked', to='userauth.UserProfile'),
        ),
        migrations.AddField(
            model_name='forum',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forums', to='forum.label'),
        ),
        migrations.AddField(
            model_name='forum',
            name='voter',
            field=models.ManyToManyField(blank=True, related_name='voted', to='userauth.UserProfile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='userauth.userprofile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.forum'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='forum.comment'),
        ),
    ]
