# Generated by Django 3.1.1 on 2020-10-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20201006_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
