# Generated by Django 3.1.1 on 2020-10-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('forum', '0002_auto_20201009_0500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['-upvotes', 'downvotes']},
        ),
        migrations.RemoveField(
            model_name='forum',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='votes',
        ),
        migrations.AddField(
            model_name='forum',
            name='downvotees',
            field=models.ManyToManyField(related_name='downvoted', to='userauth.UserProfile'),
        ),
        migrations.AddField(
            model_name='forum',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forum',
            name='upvotees',
            field=models.ManyToManyField(related_name='upvoted', to='userauth.UserProfile'),
        ),
        migrations.AddField(
            model_name='forum',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
