# Generated by Django 3.1.1 on 2020-10-06 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20201007_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['-votes']},
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='upvotees',
            new_name='voter',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='upvotes',
            new_name='votes',
        ),
    ]
