# Generated by Django 3.1.1 on 2020-10-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20201010_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={},
        ),
        migrations.RemoveField(
            model_name='forum',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='upvotes',
        ),
    ]
