# Generated by Django 3.1.1 on 2020-10-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20201007_0006'),
        ('forum', '0004_auto_20201007_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='bookmark',
            field=models.ManyToManyField(related_name='bookmark', to='userauth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='voter',
            field=models.ManyToManyField(related_name='voted', to='userauth.UserProfile'),
        ),
    ]
