# Generated by Django 3.1.1 on 2020-10-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20201005_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['-upvote']},
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='user',
            new_name='author',
        ),
    ]
