# Generated by Django 3.1.1 on 2020-10-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('forum', '0005_auto_20201005_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forum',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='userauth.userprofile'),
        ),
    ]
