# Generated by Django 3.1.1 on 2020-10-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20201007_0006'),
        ('forum', '0005_auto_20201007_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='bookmark',
            field=models.ManyToManyField(related_name='bookmarked', to='userauth.UserProfile'),
        ),
    ]
