# Generated by Django 3.1.1 on 2020-10-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.forum'),
        ),
    ]
