# Generated by Django 3.1.1 on 2020-10-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('forum', '0008_auto_20201005_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='upvotes',
            field=models.ManyToManyField(blank=True, null=True, related_name='upvoted', to='userauth.UserProfile'),
        ),
    ]
