# Generated by Django 3.1.1 on 2020-10-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('forum', '0009_forum_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvoted', to='userauth.UserProfile'),
        ),
    ]
