# Generated by Django 3.1.1 on 2020-10-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('forum', '0010_auto_20201005_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['-upvotes']},
        ),
        migrations.RemoveField(
            model_name='forum',
            name='upvote',
        ),
        migrations.AddField(
            model_name='forum',
            name='upvotees',
            field=models.ManyToManyField(related_name='upvoted', to='userauth.UserProfile'),
        ),
        migrations.RemoveField(
            model_name='forum',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='forum',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
