# Generated by Django 3.1.1 on 2020-10-05 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20201005_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forums', to='forum.label'),
        ),
    ]
